version: '3'
services:
 mysql:
  image: mysql:8
  environment:
   MYSQL_DATABASE: 'iotagram'
   MYSQL_USER: 'iotagram_db_user'
   MYSQL_PASSWORD: '3cePgRpzAZ9CQM7F'
   MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - "3306:3306"
  volumes:
   - mysql_volume:/var/lib/mysql
volumes:
 mysql_volume:
